= Завдання

. У середовищі IntelliJ IDEA створити новий проект, що містить один
головний клас Main.
. Створити тестовий клас для тестування головного класу програми.
. У головному класі описати метод, що обчислює значення функції, яка
задана у таблиці і у тестовому класі - тестові методи для нього. Діяти у
такій послідовності: спочатку створити один тестовий метод,
згенерувати метод обчислення функції. Виконати тестування та
пересвідчитись, що тест працює, тобто тестування згенерованого метода
повинно завершитися «помилкою». Реалізувати метод. Виконати
тестування. Пересвідчившись, що тест проходить, створити ще декілька
тестових методів для метода обчислення функції. Виконати тестування.
. Розробити метод, що за вказаними значеннями кроку, початку та кінця
інтервалу обчислює кількість кроків для табулювання та тестові методи
для нього і виконати тестування (порядок дій см. у п.3).
. Створити методи, що створюють масиви значень функції (y) та її
аргументу (x) в усіх точках вказаного інтервалу із заданим кроком.
(розмір масивів обчислити програмно за допомогою метода з п.4).
Створити тестові методи для них і виконати тестування (порядок дій –
см п.3).
. Створити методи, які після формування масивів, знаходять номери
найбільшого та найменшого елементів масиву значень функції, та
методи, що обчислюють та суму та середнє арифметичне елементів
масиву значень функції. Методи створювати разом з тестами та постійно
виконувати тестування.
. Створити методи виведення найбільшого та найменшого елементів
масиву значень функції, вказавши їхні номери і відповідні значення
аргументу.
. Дописати у створеному класі метод main, перетворивши, таким чином,
його на автономну програму. Cкомпілювати і виконати програму

<<<
=== Варіанти завдань


[cols="1,3,3,2,3,2"]
|===
^|Варіант ^|Функція ^|Умова ^|Вхідні дані ^|Діапазон та крок зміни аргументу ^|Номери елементів для тестування

^|1
| \[y =  \left\{
\begin{matrix}
ax^2lnx \\
1 \\
e^{ax}cosbx
\end{matrix} \right. \]
^| \[
\begin{matrix}
0.7<x\le1.4\\
x\le0.7\\
x>1.4
\end{matrix}
\]
| \[ a=-0.5\\b=2 \]
^| \[ x ϵ [0.0; 3.0] \\ \Delta x=0.004 \]
| 175, 350, 750
^|2
| \[y =  \left\{
\begin{matrix}
\pi x^2 - 7/x^2 \\
ax^3 + 7\sqrt x \\
lg(x+7\sqrt x)
\end{matrix} \right. \]
^| \[
\begin{matrix}
x\lt1.7\\
x =  1.7\\
x>1.7
\end{matrix}
\]
| \[ a=1.5 \]
^| \[ x ϵ [0.8; 2.0] \\ \Delta x=0.005 \]
| 0, 180, 240
^|3
| \[y =  \left\{
\begin{matrix}
ax^2+bx+c \\
a/x + \sqrt{x^2+1} \\
(a+bx)/ \sqrt{x^2+1}
\end{matrix} \right. \]
^| \[
\begin{matrix}
x\lt1.4\\
x =  1.4\\
x>1.4
\end{matrix}
\]
| \[ a=2.7 \\ b=-0.3 \\c=4 \]
^| \[ x ϵ [0.0; 2.0] \\ \Delta x=0.002 \]
| 0, 700, 1000
^|4
| \[y =  \left\{
\begin{matrix}
\pi x^2 - 7/x^2 \\
ax^3 + 7\sqrt x \\
ln(x+7\sqrt{\|x+a\|} )
\end{matrix} \right. \]
^| \[
\begin{matrix}
x\lt1.3\\
x =  1.3\\
x>1.3
\end{matrix}
\]
| \[ a=1.65 \]
^| \[ x ϵ [0.7; 2.0] \\ \Delta x=0.005 \]
| 0, 120, 260
^|5
| \[y =  \left\{
\begin{matrix}
1.5acos^2x \\
(x-2)^2+6a \\
3a \cdot tgx
\end{matrix} \right. \]
^| \[
\begin{matrix}
x\le0.3\\
0.3<x \le 2.3\\
x>2.3
\end{matrix}
\]
| \[ a=2.3 \]
^| \[ x ϵ [0.2; 2.8] \\ \Delta x=0.002 \]
| 50, 1050, 1300
|===